Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1304, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1020, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#@title Trajectory { display-mode: "form" }

#@markdown Reaction coordinate is $d_1 -d_2$ with 21 windows.

#@markdown Total of 2100 frames (1 ps/window, frames are saved every 1 fs.)
!rm /content/claisen.* &> /dev/null
!rm /content/*.png &> /dev/null
!pip install -U kora &> /dev/null
!wget https://github.com/cc-ats/mlp_class/raw/main/Claisen_Rearrangement/img/claisen.mp4 &> /dev/null
from kora.drive import upload_public
url = upload_public('claisen.mp4')
# then display it
from IPython.display import HTML

HTML(f"""<video src={url} width=300 controls/>""")

#@markdown <img src='https://raw.githubusercontent.com/cc-ats/mlp_class/main/Claisen_Rearrangement/img/pent-4-enal.png' width=200px>
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 10[0m
[1;32m      8[0m get_ipython()[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mpip install -U kora &> /dev/null[39m[38;5;124m'[39m)
[1;32m      9[0m get_ipython()[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mwget https://github.com/cc-ats/mlp_class/raw/main/Claisen_Rearrangement/img/claisen.mp4 &> /dev/null[39m[38;5;124m'[39m)
[0;32m---> 10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mkora[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdrive[39;00m [38;5;28;01mimport[39;00m upload_public
[1;32m     11[0m url [38;5;241m=[39m upload_public([38;5;124m'[39m[38;5;124mclaisen.mp4[39m[38;5;124m'[39m)
[1;32m     12[0m [38;5;66;03m# then display it[39;00m

[0;31mModuleNotFoundError[0m: No module named 'kora'
ModuleNotFoundError: No module named 'kora'

